fix script

diff --git a/.github/workflows/start-preview.yml b/.github/workflows/start-preview.yml
--- a/.github/workflows/start-preview.yml
+++ b/.github/workflows/start-preview.yml
@@ -38,7 +38,13 @@ jobs:
         run: mv googlecredentials.json /tmp || true
 
       - name: Locate dbt_project.yml
-        run: echo "PROJECT_DIR=$(find . -name \"dbt_project.yml\"  | sed  's/dbt_project.yml//g')" >> $GITHUB_ENV
+        run: |
+          FILE=$(find . -name "dbt_project.yml" | head -n 1)
+          if [ -z "$FILE" ]; then
+            echo "dbt_project.yml not found!" && exit 1
+          fi
+          DIR=$(dirname "$FILE")
+          echo "PROJECT_DIR=$DIR" >> $GITHUB_ENV
 
       - name: Get lightdash version 
         uses: sergeysova/jq-action@v2
